server {

    server_name localhost;
    listen 443 ssl;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/private.key;

    location / {
        proxy_pass http://myapp:8080;
        proxy_http_version 1.1;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Upgrade $http_upgrade;
    }

}

server {
    server_name localhost;
    listen 80;

    location / {
        return 301 https://localhost$request_url;
    }
}